# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.define 'machine1' do |machine|
    machine.vm.hostname = 'machine1'
    machine.vm.network "private_network", ip: "192.168.77.22"
  end

  config.vm.define 'machine2' do |machine|
    machine.vm.hostname = 'machine2'
    machine.vm.network "private_network", ip: "192.168.77.21"
  end

  config.vm.define 'machine3' do |machine|
    machine.vm.hostname = 'machine3'
    machine.vm.network "private_network", ip: "192.168.77.20"

    machine.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.verbose = true
      ansible.playbook = "test.yml"
      ansible.extra_vars = {
        role_name: Dir.pwd.split('/')[-2]
      }
    end
  end

end
